### ISSUE TITLE
Get the page_id and the access token to pass as parameters to this script

### ISSUE THREAD

**Issue by joslangarica** [eisenjulian/fb-page-chat-download#1]
Hello, sorry i'm a newby 
Can you help me understand this "Get the page_id and the access token to pass as parameters to this script" 

Where should i put the page_id and the access token ?
Regards!

**Comment by eisenjulian** [comment]
@joslangarica if you already got the page_id and the access token just paste them into your terminal when you run the python script as follows:

`python fb-page-chat-download/run.py PASTE_PAGE_ID PASTE_OUTPUT_FILE PASTE_ACCESS_TOKEN`

Good luck!
