### ISSUE TITLE
TypeError: file() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by Cerpint4xt** [eisenjulian/fb-page-chat-download#12]
Hey Eisen, hope you are really fine but i would like to know if you are abe to help me with this scraper you kinddly wrote. I've used the scraper one year ago actually and it ran perfectly, now im getting an error that i should pass 3 arguments and according to the error I'm passing 4 but i got just the page_id the name of the file and finally the access_token. I don't know what exactly could have been change but i would really help me if you could just take a look and help me out please 
![error](https://user-images.githubusercontent.com/33381390/81477101-27a0b200-9216-11ea-82d5-3d36ee869840.png)

**Comment by eisenjulian** [comment]
Hello @Cerpint4xt that error indicates that you are running from Python 2 runtime, where the `open` method didn't have some of arguments. If you use Python 3 the problem should go away. The version is printed if you open python without arguments.

**Comment by Cerpint4xt** [comment]
Ohhh I'm really sorry i forgot about that, anyway i manage to get it work Thanks a lot, but I'm stil having some problems with since and until argument, it says unrecognize argument and i read in other issue that the since and  until were timestamps like epoch timestamps, i.e. 1589107425 for the "now" timestamp
