### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eorione** [eisenjulian/fb-page-chat-download#5]
Acabo de descargar el script y me aparece esto al ejecutarlo:

![image](https://user-images.githubusercontent.com/10728747/39365011-4cf4814e-4a06-11e8-8dcd-896117cf2a2d.png)

**Comment by eisenjulian** [comment]
Hello @eorione, were you able to solve this?

**Comment by eisenjulian** [comment]
The issue cannot be reproduced. Closing
