### ISSUE TITLE
file() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by anarmammad** [eisenjulian/fb-page-chat-download#9]

**Comment by eisenjulian** [comment]
Please use python3 instead of python2 to run this

**Comment by anarmammad** [comment]
Thanks a lot, already noticed!

**Comment by anarmammad** [comment]
Your script is working great! But i would like to clarify the use of
parameters *since* and *until. *Should they be str type? Or if they
shouldn’t how to pass the date to the script in int?

**Comment by eisenjulian** [comment]
It's an epoch, that is the number of seconds since Jan 1, 1970. Feel free to update the README to make it more clear.
